### PR TITLE
MNT Add config key for Versioned extension applied to File

### PR DESCRIPTION
**Pull request by michalkleiner**
Add named key to the config where Versioned is applied to File so that the extension can be removed through custom config if needed.

### CODE REVIEW

**Comment by michalkleiner** [comment]
Not sure if this should target `2` or `2.0`, can retarget if needed.

**Comment by GuySartorelli** [comment]
Retargetted to `2.0` - this doesn't break (or even really materially change) anything so happy for it to be part of the initial release.

@michalkleiner looks like retargetting has dragged along some unrelated commits

**Comment by michalkleiner** [comment]
I'll rebase it, just a sec

**Review by GuySartorelli — APPROVED** [review]
Nice, thanks!
Ignoring CI failures from PUSH because the ones related to the PR itself are passing.

**Pull request merged**
