### PR TITLE
FIX Do not update LeftAndMain link with Stage param

### PR DESCRIPTION
**Pull request by maxime-rainville**
Add a condition so we don't try to add Stage URL param to LeftAndMain links.

Fixes https://github.com/silverstripe/silverstripe-admin/issues/607

### CODE REVIEW

**Comment by dhensby** [comment]
This is a bit gross as we're mixing knowledge about modules in a way we shouldn't.

It would be much nicer to have a way for `LeftAndMain` to disable this link re-writing; can't we disable/remove the extension for the LeftAndMain controller?

**Comment by lukereative** [comment]
Any further suggestions @robbieaverill on this regarding @dhensby's comment and my reply?

**Comment by robbieaverill** [comment]
@lukereative yeah I've been thinking about this. I thought about maybe moving the extension point from RequestHandler to something higher in the chain, but then we risk breaking people's code that extends low level classes like this and expects versioned capability.

I personally don't mind the coupling, particularly when there's no great alternative. @dhensby do you have any ideas?

**Comment by lukereative** [comment]
@chillu has asked this be merged as it's `impact/critical` and since the only pushback is semantic (which doesn't seem to be that avoidable either) rather than anything regarding the function of the fix – we can fix this up later if a better way presents itself.

**Comment by ScopeyNZ** [comment]
Can we get this merged up to `1` please?

**Pull request merged**
