### PR TITLE
BUGFIX: Ensure scalar plugin is assigned to Version field

### PR DESCRIPTION
**Pull request by unclecheese**
Fixes https://github.com/silverstripe/silverstripe-graphql/issues/404

### CODE REVIEW

**Comment by emteknetnz** [comment]
@unclecheese I've retargetted to 1.9 - could you please rebase

**Comment by unclecheese** [comment]
Done

**Review by emteknetnz — CHANGES_REQUESTED** [review]
Page history is still hanging even with this fix :-/

**Comment by unclecheese** [comment]
You've rebuilt the admin schema?

**Review by emteknetnz — APPROVED** [review]

**Pull request merged**
