### PR TITLE
Pulls/1/gridfield versioned default

### PR DESCRIPTION
**Pull request by phalkunz**
Issue: https://github.com/silverstripe/silverstripe-versioned/issues/64

### CODE REVIEW

**Comment by tractorcow** [comment]
No, this is NOT meant to be opt-out. See https://github.com/silverstripe/silverstripe-versioned/issues/21 for the discussion.

This should only be turned on by default for the modeladmin section, not all gridfields everywhere.

**Comment by dhensby** [comment]
hmm, it's causing a lot of discord in the community that versioned objects don't automatically get versioned actions in the gridfields that display them.. why do we want to make this opt-in when it effectively breaks the gridfield actions on versioned objects?

main complaint I'm aware of is using a gridfield to delete a versioned record results in a deletion from draft site and it disappears from the gridfield, then there's no way to delete from live and so we see an inconsistent state in the CMS vs the live site.

**Comment by tractorcow** [comment]
I'm just going to leave it... I had originally made it on-by-default, and was requested to turn it off by default, and have it be opt-in. It probably should just be on by default.

@phalkunz for you to look at once you get back.

**Comment by dhensby** [comment]
@tractorcow you're first instinct is usually the right one ;)

**Pull request merged**
