### PR TITLE
API Remove Versioned_Version class and Versioned::allVersions() method

### PR DESCRIPTION
**Pull request by tractorcow**
Related: https://github.com/silverstripe/silverstripe-framework/issues/7663 (implements 5.0 changes only)

- [x] Changelog PR: https://github.com/silverstripe/silverstripe-framework/pull/7737
- [ ] CMS PR: https://github.com/silverstripe/silverstripe-cms/pull/2065

### CODE REVIEW

**Comment by robbieaverill** [comment]
Needs a rebase, and also could we add `@deprecated` PHPDocs in 4.1 for the methods that are removed?

**Comment by tractorcow** [comment]
I don't really want to back-port the functionality to 4.1; If we deprecated it, we would need to remove usages at the same time.

**Comment by robbieaverill** [comment]
Yeah fair enough

**Comment by tractorcow** [comment]
Rebased.

**Pull request merged**
