### PR TITLE
FIX Reset reading stage when user logs out of the CMS

### LINKED ISSUE #62: Stage should be reset to Live when logging out of the CMS
`Versioned::chose_site_stage` will use the session variable `readingMode` if it's present, which means that if it's previously set to Draft then a user logs out of the CMS, SS will still (attempt to) show draft content after this.

Failing test showing the problem:

```diff
diff --git a/tests/php/VersionedTest.php b/tests/php/VersionedTest.php
index 837d9f5..cca2531 100644
--- a/tests/php/VersionedTest.php
+++ b/tests/php/VersionedTest.php
@@ -15,6 +15,7 @@ use SilverStripe\ORM\DataObject;
 use SilverStripe\ORM\DataObjectSchema;
 use SilverStripe\ORM\DB;
 use SilverStripe\ORM\FieldType\DBDatetime;
+use SilverStripe\Security\IdentityStore;
 use SilverStripe\Versioned\ChangeSet;
 use SilverStripe\Versioned\Versioned;
 
@@ -1022,6 +1023,13 @@ class VersionedTest extends SapphireTest
         $request->getSession()->clear('readingMode');
         Versioned::choose_site_stage($request);
         $this->assertEquals('Stage.Live', Versioned::get_reading_mode());
+
+        // Ensure stage is reset to Live when logging out
+        $request->getSession()->set('readingMode', 'Stage.Stage');
+        Versioned::choose_site_stage($request);
+
+        Injector::inst()->get(IdentityStore::class)->logOut($request);
+        $this->assertSame('Stage.Live', Versioned::get_reading_mode());
     }
 
     /**

```

For reference, SS3 does reset the reading mode when logging out (see `Member::logOut`):

```php
		// Switch back to live in order to avoid infinite loops when
		// redirecting to the login screen (if this login screen is versioned)
		Session::clear('readingMode');
```

### PR DESCRIPTION
**Pull request by robbieaverill**
Fixes #62 

Requires https://github.com/silverstripe/silverstripe-framework/pull/7547

### CODE REVIEW

**Comment by dhensby** [comment]
This needs a partial revert once https://github.com/silverstripe/silverstripe-framework/pull/7552 is merged.

There should never be leaking of sessions after logout

**Comment by robbieaverill** [comment]
Sounds good. We could either revert this whole commit, or just the extension and leave the tests. That core fix is much better :)

**Comment by dhensby** [comment]
@robbieaverill time for that revert?

**Comment by robbieaverill** [comment]
@dhensby (cc @flamerohr) extension removed in PR #65

**Comment by flamerohr** [comment]
Lets merge that after stable release - it's harmless as is

**Comment by robbieaverill** [comment]
How semantic do you want to be about it though ;)

**Pull request merged**
