### PR TITLE
Compliance with new graphql resolvedTypeName() method

### PR DESCRIPTION
**Pull request by unclecheese**
Partial resolution of https://github.com/silverstripe/silverstripe-graphql/pull/176
Depends on https://github.com/silverstripe/silverstripe-graphql/pull/182

### CODE REVIEW

**Comment by unclecheese** [comment]
Yeah good point. Not the first time this has come up, either. We have so many modules that aren't necessarily direct dependencies of each other, but they are by proxy. In this case `silverstripe/admin` is the glue between the two, which is likely installed, but not required. When it is, it would enforce that constraint.

I'm not sure about doing it procedurally. Seems like any solution would be pretty ugly. The `Module` class doesn't offer a `getVersion` API or anything. 

Any thoughts on how we might do it? I'm open to ideas.

**Comment by maxime-rainville** [comment]
What about adding a `conflict` in on the packages? https://getcomposer.org/doc/04-schema.md#conflict

**Comment by maxime-rainville** [comment]
Ping @unclecheese :cat:

**Comment by emteknetnz** [comment]
@unclecheese  I'm currently going through some old pull-requests to see what is still active and what makes sense to be closed - is this one something you're still planning on keeping active or would you prefer to now close this one?

**Comment by Cheddam** [comment]
@unclecheese Closing this out for now - if it makes sense to reapproach later feel free to reopen.

**Pull request closed without merging**
