### PR TITLE
BUG Add admin module to build configuration

### PR DESCRIPTION
**Pull request by tractorcow**

### CODE REVIEW

**Comment by sminnee** [comment]
I don't quite see why this is necessary, or why the framework tests are part of the versioned test run.

**Comment by tractorcow** [comment]
👍

**Comment by chillu** [comment]
Four +1s on Sam's alternative suggestion (incl. me), so closing this

**Comment by tractorcow** [comment]
Admin module is still needed; We should have just removed the tests, not the actual .travis.yml fix.

**Pull request closed without merging**
