### PR TITLE
Tighten up DB index definitions

### PR DESCRIPTION
**Pull request by dhensby**
Tightening up DB index definitions

### CODE REVIEW

**Comment by dhensby** [comment]
test pass locally with mysql (no pdo):

```
[root@localhost html]# vendor/bin/phpunit versioned/tests/php/ --stop-on-error
PHPUnit 5.7.19 by Sebastian Bergmann and contributors.

.........S....................................................... 65 / 67 ( 97%)
..                                                                67 / 67 (100%)

Time: 42.01 seconds, Memory: 50.00MB
```

test pass locally with mysql_pdo:

```
[root@localhost html]# vendor/bin/phpunit versioned/tests/php/ --stop-on-error
PHPUnit 5.7.19 by Sebastian Bergmann and contributors.

.........S....................................................... 65 / 67 ( 97%)
..                                                                67 / 67 (100%)

Time: 1.01 minutes, Memory: 50.00MB
```

**Comment by dhensby** [comment]
Tests pass locally with postgres (no pdo):

```
[root@localhost html]# vendor/bin/phpunit versioned/tests/php/ --stop-on-error
PHPUnit 5.7.19 by Sebastian Bergmann and contributors.

.........S....................................................... 65 / 67 ( 97%)
..                                                                67 / 67 (100%)

Time: 1.98 minutes, Memory: 50.00MB
```

**Comment by chillu** [comment]
@dhensby Tests are still failing

**Comment by dhensby** [comment]
Yep, the tests will fail until all the PRs are merged

**Comment by dhensby** [comment]
*the Travis builds

**Comment by dhensby** [comment]
🎉

**Pull request merged**
