### PR TITLE
API Rescue Master Branch PR: Support new extend*() format for extension methods

### PR DESCRIPTION
**Pull request by GuySartorelli**
Rescues https://github.com/silverstripe/silverstripe-versioned/pull/84

## Dependencies
- Requires https://github.com/silverstripe/silverstripe-framework/pull/10457 to be merged first

## Parent issue
- https://github.com/silverstripe/silverstripe-framework/issues/10350

### CODE REVIEW

**Comment by emteknetnz** [comment]
Re-running tests now that dependent PR has been merged

**Comment by GuySartorelli** [comment]
Needs https://github.com/silverstripe/silverstripe-asset-admin/pull/1290 and https://github.com/silverstripe/silverstripe-postgresql/pull/135 to be merged for CI to go green.

**Comment by emteknetnz** [comment]
Merged both, rerunning tests

**Comment by emteknetnz** [comment]
Still failing

**Comment by GuySartorelli** [comment]
The current CI failure will be resolved when https://github.com/silverstripe/silverstripe-framework/pull/10479 is merged (though there will likely be others after that)

**Review by emteknetnz — APPROVED** [review]

**Pull request merged**
