### PR TITLE
Edit form action buttons improved.

### PR DESCRIPTION
**Pull request by mfendeksilverstripe**
* button UI is now more consistent with other parts of CMS (Page Edit form)
* save button indicates form input change
* publish button reflects published state
* last edited and last published dates are now displayed in the `more options` widget
* unpublish and archive button have confirmation

## Related issues

https://github.com/silverstripe/silverstripe-versioned/issues/255

## Related PRs

https://github.com/silverstripe/silverstripe-versioned/pull/242

This is how it looks like:

alt text
alt text
alt text
alt text

### CODE REVIEW

**Comment by unclecheese** [comment]
This looks great. Would you mind posting a few screenshots so @silverstripe/designers Can have a look?

**Comment by mfendeksilverstripe** [comment]
@unclecheese Thanks for the feedback. I will look into this at the next opportunity :).

**Comment by unclecheese** [comment]
This is what I'm seeing. (Ignore the missing icon. I think that's on me)

Publish button appears to be in the wrong place, and the popup goes off the screen.

Screenshot 2019-04-15 16 37 08

**Comment by ScopeyNZ** [comment]
This PR will need to be retargetted at `master` as a minor change.

**Comment by mfendeksilverstripe** [comment]
@unclecheese I added some screenshots, please have a look.

@ScopeyNZ  Tried to rebase on master, but there are a lot of conflicts to resolve. WIll look at it later.

**Comment by robbieaverill** [comment]
Sorry @mfendeksilverstripe, master is for breaking changes. You should target the `1` branch =)

**Comment by mfendeksilverstripe** [comment]
@robbieaverill Switched to `1` as a base.

**Comment by mfendeksilverstripe** [comment]
@unclecheese Could you please check your error log? The broken layout is most likely caused by missing a required file. Did you run `vendor-expose` and `flush`?

**Comment by mfendeksilverstripe** [comment]
@unclecheese  Any updates on this PR?

**Comment by unclecheese** [comment]
Getting there. Looks like the publish button is not in the right place. This is likely due to the upstream changes in `VersionedGridFieldItemRequest`. Can you please rebase?

Screenshot 2020-01-31 10 59 46

**Comment by mfendeksilverstripe** [comment]
@unclecheese It's now rebased, could you please have another look?

**Comment by robbieaverill** [comment]
Hey team, I just noticed that this PR essentially introduces a frontend component to this module. It's always been a backend only module, which is why silverstripe/versioned-admin exists. Can we move the frontend code to that module? Or is it going to be too much work now?

**Comment by mfendeksilverstripe** [comment]
Interesting observation. I think we should be able to move it to the versioned-admin module.

**Comment by robbieaverill** [comment]
That'd be lovely if you get some time. Luckily we don't really consider our JS as part of our semver commitments yet.

Sorry for not picking this up at review stage.

**Comment by emteknetnz** [comment]
@mfendeksilverstripe 
Do we still need this PR or can we close this one?

**Pull request merged**
